### PR TITLE
Remove paxtools-trove

### LINKED ISSUE #51: GNU Trove is deprecated. Remove paxtools-trove?
As GNU Trove4j is [deprecated](https://bitbucket.org/trove4j/trove/src/master/) perhaps the paxtools-library should be removed?

### PR DESCRIPTION
**Pull request by MaybeJustJames**
GNU Trove is deprecated. If you need alternative high performance
collections the GNU Trove author recommends:
* Eclipse Collections (http://www.eclipse.org/collections/) or
* HPPC (https://github.com/carrotsearch/hppc)

Trove4j deprecation notice: https://bitbucket.org/trove4j/trove/src/master/

Closes #51

### CODE REVIEW

**Comment by IgorRodchenkov** [comment]
I doubt it's necessary to remove trove. It's an optional runtime dependency, one does not have to use it in other projects. The paxtools-console does use it, but it's fine - developers should not add this executable fat jar or this module as dependency to other projects (it's supposed to be run from console, not to be part of other s/w). But if we'd like to proceed to get rid of the library and module, we should at least increment the Paxtools version from current 5.2.1-SNAPSHOT to at least 5.3.1-SNAPSHOT.

**Comment by MaybeJustJames** [comment]
Ok. I understand. I've bumped the version as you suggested so you can decide to merge or not.

**Comment by IgorRodchenkov** [comment]
Let's reject this PR for now, keep it as is (paxtools also need to be updated and tested with JDK18, perhaps new HP collections provider, if any, etc).

**Comment by IgorRodchenkov** [comment]
On the second/third thought, why not - let's do this now (get rid of the module and dependency) - one can still simply implement a BPCollections.CollectionProvider in own project using collections lib of their choice and enable using JVM option "paxtools.CollectionProvider=<classname>". 
@MaybeJustJames  could you please change from 5.3.1- to 5.3.0-SNAPSHOT in all the pom.xml files before we merge it?

**Comment by IgorRodchenkov** [comment]
Won't do - there is another PR, more changes. Thank you!

**Pull request closed without merging**
